### ISSUE TITLE
similarity fit overflow

### ISSUE THREAD

**Issue by EleSpine** [moldyn/MoSAIC#9]
Hi everyone,

First of all congratulations on all your work on this exciting tool.

I have an input numpy array of shape (5852, 1297) and this is in the format (n_samples, n_features).
If I do:

```
d_array = np.load(“data”)
sim = mosaic.Similarity(
    metric='correlation’)
sim.fit(d_array]) 
```

I get:
_ValueError: Correlation matrix is not symmetric. This should not occur and is probably caused by an overflow error._

The procedure actually works only if I reduce a lot the input matrix, as much as I can keep only 200 features.
The funny fact is that I, by mistake, transposed the matrix, so to get d_array of dimensions (1297, 5852) and in that case, it worked perfectly, but of course, it was conceptually wrong.

I tried to work around the problem by computing the correlation matrix with standard numpy:
`R1 = np.corrcoef(d_array.T)
`
With this, I get the correlation matrix, but if I then feed this to the clustering function I get an error:
_AssertionError: False not tri-state boolean._

As suggested by Georg Diez, I checked the format of my input data and it is np.float32.

Could you help me with this problem?

Thank you,
Elena

**Comment by braniii** [comment]
Hi Elena,

glad you want to try MoSAIC and thank for finding this bug. The issue was that using `np.allclose` has an absolute tolerance of `1e-8`. Using `np.float16` or `np.float32` floating point inaccuracy can lead to larger errors. Now the code adjusts the absolute tolerance according to the precision of the input, so it should be fixed by #10.

And now to the second part. The clustering routine requires a similarity measure defined within range $[0, 1]$. Hence, one needs to use the absolute value of the correlation. Here is a minimal working example (after merging #10):
```Python
import mosaic
import numpy as np

# create random trajectory
n_samples, n_features = 1000, 1000
np.random.seed(42)
traj = np.random.normal(size=(n_samples, n_features))

# estimate correlation
# via MoSAIC
corr = mosaic.Similarity().fit_transform(traj)
# via np
corr_np = np.corrcoef(traj, rowvar=False)

# cluster result
clust = mosaic.Clustering().fit(corr_np)
# gives error the AssertionError: False not tri-state boolean.
clust = mosaic.Clustering().fit(np.abs(corr_np))
# executes as expected
clust = mosaic.Clustering().fit(corr)
```

And I guess the `AssertionError` is an issue of `beartype`, I opend an issue there beartype/beartype#153. Normally one should get the error:
```Python traceback
False == Is[lambda arr: np.all(arr >=0)].
```
which is not perfect, but much clearer.

I Hope I could help you. I will close the issue for now. If the error persists after upgrading to `v0.3.1` please reopen it. I will push the new version today to PyPI and hopefully tomorrow to conda-forge.

Best
Daniel

**Comment by EleSpine** [comment]
Hi Daniel,

thank you very much for your quick fix and reply. 
I will try it again as soon as possible.

All the best,
Elena

**Comment by braniii** [comment]
The beartype author has once again shown that the fault lies not with her but with numpy. The issue was that `np.all` is not return a boolean instead it returns `np.bool_`. I fixed this issue in the development branch. But it will take some weeks until it will land in a new release.

If you encounter further issues, I would thankful for letting me now.

Best
Daniel
